"""Dictionary-learning utilities used by TEXTER."""

from .metrics import (
    avg_l1_loss,
    avg_l2_loss,
    cosine_hungarian_loss,
    dead_codes,
    dictionary_collinearity,
    frechet_distance,
    hoyer,
    hungarian_loss,
    kappa_4,
    l0,
    l1,
    l2,
    lp,
    r2_score,
    relative_avg_l1_loss,
    relative_avg_l2_loss,
    wasserstein_1d,
)
from .models import ConvNeXt, DinoV2, ResNet, SigLIP, ViT
from .optimization import (
    ConvexNMF,
    NMF,
    SemiNMF,
    SkDictionaryLearning,
    SkICA,
    SkKMeans,
    SkNMF,
    SkPCA,
    SkSVD,
    SkSparsePCA,
)
from .sae import (
    AttentionEncoder,
    BatchTopKSAE,
    DictionaryLayer,
    EncoderFactory,
    JumpSAE,
    MLPEncoder,
    RelaxedArchetypalDictionary,
    ResNetEncoder,
    SAE,
    TopKSAE,
)
from .visualization import (
    contour_top_image,
    evidence_top_images,
    overlay_top_heatmaps,
    zoom_top_images,
)

__version__ = "0.2.8"

__all__ = [
    "AttentionEncoder",
    "BatchTopKSAE",
    "ConvNeXt",
    "ConvexNMF",
    "DictionaryLayer",
    "DinoV2",
    "EncoderFactory",
    "JumpSAE",
    "MLPEncoder",
    "NMF",
    "RelaxedArchetypalDictionary",
    "ResNet",
    "ResNetEncoder",
    "SAE",
    "SemiNMF",
    "SigLIP",
    "SkDictionaryLearning",
    "SkICA",
    "SkKMeans",
    "SkNMF",
    "SkPCA",
    "SkSVD",
    "SkSparsePCA",
    "TopKSAE",
    "ViT",
    "avg_l1_loss",
    "avg_l2_loss",
    "contour_top_image",
    "cosine_hungarian_loss",
    "dead_codes",
    "dictionary_collinearity",
    "evidence_top_images",
    "frechet_distance",
    "hoyer",
    "hungarian_loss",
    "kappa_4",
    "l0",
    "l1",
    "l2",
    "lp",
    "overlay_top_heatmaps",
    "r2_score",
    "relative_avg_l1_loss",
    "relative_avg_l2_loss",
    "wasserstein_1d",
    "zoom_top_images",
]
